/**
 * @created On: 10 March 2014.
 * @version: 1
 * Student ID:W1093927,W1077339
/////////////////////////////////////////////////////////////////////
///  mainWindow.java  -  Demonstrate mainWindow Class            //
///                                                                //
///  Language:    Java                                             //
///  Platform:    Lenovo G500, Windows 8 .                         //
///  Application: COEN 275 -OO Analysis, Design & Programming,     //
///               Winter 2014                                      //
///  Instructor:  Dr.Rani Mikkilineni, Santa Clara University      //
///                                                                //
///  @author:      Priyanka Tayade, Santa Clara University         //
///               (315) 416-0205, ptayade@scu.edu  
                   Geethika Kilaru,Santa Clara University
                   408-458-0234, gkilaru@scu.edu
//
///                                                                //
///  Purpose:    main ui                                           //
///                                                                // 
/////////////////////////////////////////////////////////////////////
///
 */
/*
 * Maintenance : Original
 * Modified On:--
 * Modified By:--
 * Purpose:--
 */

package ecoRceycleGui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.List;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JTabbedPane;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.table.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;

import org.ietf.jgss.MessageProp;

import connection.selectQueries;
import connection.sqlConnection;

/**
 *
 * @author Priyanka
 */
@SuppressWarnings("serial")
public class mainWindow extends javax.swing.JFrame  {

	
    /**
     * Creates new form simulationWindow
     * @throws SQLException 
     */
    public mainWindow() throws SQLException {
        initComponents();
    }
    Statement stm;
    Statement stm2;
    Vector columnNames = new Vector();
    Vector data = new Vector();
    Object [][] list=new Object[][]{{"PAPER",0},{"GLASS",1},{"PLASTIC",2},{"ALUMINIUM",3}};
	private  sqlConnection connnect;
	private selectQueries sql;
	private String[] RCM;
	static private String D1=null;
	private String D2=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
	public void setDate1(String Text)
	{
		 //JOptionPane.showMessageDialog(null,Text,"TITLE",JOptionPane.WARNING_MESSAGE);
			D1=Text;
		/* jNewButton3Stat.setText(D1);
		 jNewButton3Stat.setBounds(90, 160, 59, 20);
	     jLayeredPane1Stat.add(jNewButton3Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);*/
	}
	
    @SuppressWarnings({ "unchecked", "rawtypes" })
    private void initComponents() throws SQLException {
    	
    	validator val=new validator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new JPanel();
        jTabbedPane1 = new JTabbedPane();
       
        jTabbedPane3 = new JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new  javax.swing.JTable();
        jLabel1 = new  JLabel();
        jLabel4 = new JLabel();
        jLabel7 = new JLabel();
        
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        
        jLabel5 = new javax.swing.JLabel();
        jPanel50 = new JPanel();
        
        /// For Rcm one Declaration
		//jLayeredPane1RCM1 = new javax.swing.JLayeredPane();
        //jLabel9RCM1 = new javax.swing.JLabel();
        jPanel1RCM1 = new javax.swing.JPanel();
        jLabel1RCM1 = new javax.swing.JLabel();
        jTextField1RCM1 = new javax.swing.JTextField();
        jComboBox1RCM1 = new javax.swing.JComboBox();
        jLabel2RCM1 = new javax.swing.JLabel();
        jLabel3RCM1 = new javax.swing.JLabel();
        jRadioButton1RCM1 = new javax.swing.JRadioButton();
        jRadioButton2RCM1 = new javax.swing.JRadioButton();
        jLabel4RCM1 = new javax.swing.JLabel();
        jLabel5RCM1 = new javax.swing.JLabel();
        jLabel6RCM1 = new javax.swing.JLabel();
        jScrollPane1RCM1 = new javax.swing.JScrollPane();
       // jTable1RCM1 = new javax.swing.JTable();
        button1RCM1 = new java.awt.Button();
        textField1RCM1 = new java.awt.TextField();
        label1RCM1 = new java.awt.Label();
        jButton1RCM1 = new javax.swing.JButton();
        jButton2RCM1 = new javax.swing.JButton();
        jButton3RCM1 = new javax.swing.JButton();
        jButton4RCM1 = new javax.swing.JButton();
        jLabel7RCM1 = new javax.swing.JLabel();
        jLabel8RCM1 = new javax.swing.JLabel();
        
        // For RCM 2-----Declaration
        jPanel1RCM2 = new javax.swing.JPanel();
        jLabel1RCM2 = new javax.swing.JLabel();
        jtextField1RCM2 = new javax.swing.JTextField();
        jComboBox1RCM2 = new javax.swing.JComboBox();
        jLabel2RCM2 = new javax.swing.JLabel();
        jLabel3RCM2 = new javax.swing.JLabel();
        jRadioButton1RCM2 = new javax.swing.JRadioButton();
        jRadioButton2RCM2 = new javax.swing.JRadioButton();
        jLabel4RCM2 = new javax.swing.JLabel();
        jLabel5RCM2 = new javax.swing.JLabel();
        jLabel6RCM2 = new javax.swing.JLabel();
        jScrollPane1RCM2 = new javax.swing.JScrollPane();
        button1RCM2 = new java.awt.Button();
        textField1RCM2 = new java.awt.TextField();
        label1RCM2 = new java.awt.Label();
        jButton1RCM2 = new javax.swing.JButton();
        jButton2RCM2 = new javax.swing.JButton();
        jButton3RCM2 = new javax.swing.JButton();
        jButton4RCM2 = new javax.swing.JButton();
        jLabel7RCM2 = new javax.swing.JLabel();
        jLabel8RCM2 = new javax.swing.JLabel();
        
        jLayeredPane1AddRcm = new javax.swing.JLayeredPane();
        jButton2AddRcm = new javax.swing.JButton();
        jButton1AddRcm = new javax.swing.JButton();
        jTextField3AddRcm = new javax.swing.JTextField();
        jTextField4AddRcm = new javax.swing.JTextField();
        jLabel6AddRcm = new javax.swing.JLabel();
        jLabel5AddRcm = new javax.swing.JLabel();
        jLabel4AddRcm = new javax.swing.JLabel();
        jTextField2AddRcm = new javax.swing.JTextField();
        jLabel3AddRcm = new javax.swing.JLabel();
        jLabel1AddRcm = new javax.swing.JLabel();
        jScrollPane1AddRcm = new javax.swing.JScrollPane();
        jList1AddRcm = new javax.swing.JList();
        
    	jScrollPane1Service = new javax.swing.JScrollPane();
        jList1Service = new javax.swing.JList();
        jComboBox1Service = new javax.swing.JComboBox();
        jComboBox2Service = new javax.swing.JComboBox();
        jTextField1Service = new javax.swing.JTextField();
        jLabel1Service = new javax.swing.JLabel();
        jLabel2Service = new javax.swing.JLabel();
        jLayeredPane1Service = new javax.swing.JLayeredPane();
        jButton1Service = new javax.swing.JButton();
        jButton2Service = new javax.swing.JButton();
        
        

        jLayeredPane1Stat = new javax.swing.JLayeredPane();
        jLabel1Stat = new javax.swing.JLabel();
        jLabel2Stat = new javax.swing.JLabel();
        jRadioButton1Stat = new javax.swing.JRadioButton();
        jRadioButton2Stat = new javax.swing.JRadioButton();
        jLabel3Stat = new javax.swing.JLabel();
        jLabel4Stat = new javax.swing.JLabel();
        jButton5Stat = new javax.swing.JButton();
        //jNewButton3Stat = new javax.swing.JTextField();
        jNewButton4Stat = new javax.swing.JComboBox();
        jButton6Stat = new javax.swing.JTextField();
        jButton1Stat = new javax.swing.JButton();
        jButton2Stat = new javax.swing.JButton();
        jComboBox1Stat = new javax.swing.JComboBox();
        jComboBox2Stat = new javax.swing.JComboBox();
        jLabel7Stat = new javax.swing.JLabel();
        jComboBox3Stat = new javax.swing.JComboBox();
        
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        try
        {
            //  Connect to an Access Database

        	sqlConnection connect2= new sqlConnection();
          	 Connection conn=connect2.connect();
          
           Statement    stm = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE); 
            //  Read data from a table

            String sql = "Select rcm_id,location,status from rcm";
        
            
            ResultSet rs3 = stm.executeQuery( sql );
            ResultSetMetaData md = rs3.getMetaData();
            int columns = md.getColumnCount();

            //  Get column names
               int i=1;
            for (; i <= columns; i++)
            {
                columnNames.addElement( md.getColumnName(i) );
                
            }
            
            columnNames.addElement("    ");
            columnNames.addElement("    ");
            

            //  Get row data

            while (rs3.next())
            {
                Vector row = new Vector(columns);

                for (int k = 1; k <= columns; k++)
                {
                    row.addElement( rs3.getObject(k) );
                }
                   row.addElement("Details");
                   row.addElement("Delete");
                   data.addElement( row );
            }

            rs3.close();
            stm.close();
            conn.close();
        }
        catch(Exception e)
        {
            System.out.println( e );
        }
 	   JTable table = new JTable(data, columnNames)
     {
         public Class getColumnClass(int column)
         {
             for (int row = 0; row < getRowCount(); row++)
             {
                 Object o = getValueAt(row, column);

                 if (o != null)
                 {
                     return o.getClass();
                 }
             }

             return Object.class;
         }
     };
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        
        Image image = Toolkit.getDefaultToolkit().getImage("../Latest/images/giphy.gif");

        ImagePanel imagePanel = new ImagePanel(image);

        imagePanel.add(new JLabel("Some label"));
        //frame.add(imagePanel);
        jLabel5.setIcon(new javax.swing.ImageIcon("../Latest/images/basic3.jpg")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel5.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        
        jLabel7.setIcon(new javax.swing.ImageIcon("../Latest/images/blue title bar.jpg")); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("../Latest/images/blue title bar.jpg")); // NOI18N
        
        jLabel4.setIcon(new javax.swing.ImageIcon("../Latest/images/logoutlogout.png")); // NOI18N
        //recycle-bin-hi, logout-latest
        jLabel7RCM1.setIcon(new javax.swing.ImageIcon("../Latest/images/trash_green.png")); // NOI18N
        jLabel8RCM1.setIcon(new javax.swing.ImageIcon("../Latest/images/paper.jpg")); // NOI18N
    
        jLabel7RCM2.setIcon(new javax.swing.ImageIcon("../Latest/images/trash_green.png")); // NOI18N
        jLabel8RCM2.setIcon(new javax.swing.ImageIcon("../Latest/images/paper.jpg")); // NOI18N
        
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        jScrollPane1.setMaximumSize(new java.awt.Dimension(327, 327));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(45, 32));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sr No", "RCM ID", "Location", "Status", "Last Emptied", "--", "--"
            }
        ));
        
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        Action newWindow = new AbstractAction()  //Action for Details Button
        {
            public void actionPerformed(ActionEvent e)
            {
                JTable table = (JTable)e.getSource();
                int modelRow = Integer.valueOf( e.getActionCommand() );
                int s = (int)table.getModel().getValueAt(modelRow, 0);
                editRCM ec = new editRCM(s);
                
            }
             };
             
             
             Action delete = new AbstractAction()  //Action for Delete Button
             {
                 public void actionPerformed(ActionEvent e)
                 {
                     JTable table = (JTable)e.getSource();
                     int modelRow = Integer.valueOf( e.getActionCommand() );
                     int s = (int)table.getModel().getValueAt(modelRow, 0);
                     
                     
                     DefaultTableModel model = (DefaultTableModel)table.getModel();
                     JOptionPane.showMessageDialog(null,"RCM WILL BE PERMANENTLY DELETED","NOTE",JOptionPane.WARNING_MESSAGE);
                     model.removeRow(modelRow);
                     
                     
                    
                     
                     
                     
                 }
                  };
        ButtonColumn bc = new ButtonColumn(table,newWindow,3);
        ButtonColumn bc2 = new ButtonColumn(table,delete,4);
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        jScrollPane1.setViewportView(table);
        jTable1.getColumnModel().getColumn(0).setMinWidth(45);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(45);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(45);

        //----------------------
        jButton2AddRcm.setText("Clear");
        jButton2AddRcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jTextField3AddRcm.setText("       ");
            	jTextField4AddRcm.setText("      ");
            	jTextField2AddRcm.setText("      ");
               
            }
        });
        jButton2AddRcm.setBounds(190, 150, 70, 23);
        jLayeredPane1AddRcm.add(jButton2AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);

        jButton1AddRcm.setText("Save");
        jButton1AddRcm.setBounds(110, 150, 57, 23);
        jLayeredPane1AddRcm.add(jButton1AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);
        jTextField3AddRcm.setBounds(110, 0, 90, 20);
        jLayeredPane1AddRcm.add(jTextField3AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);
        jTextField4AddRcm.setBounds(110, 120, 90, 20);
        jLayeredPane1AddRcm.add(jTextField4AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);
        
        
        jButton1AddRcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
          	 // if()
          	  String textFieldValue1 =jTextField3AddRcm.getText(); //location
          	String textFieldValue2 =jTextField4AddRcm.getText();  // Weight
          	String textFieldValue3 =jTextField2AddRcm.getText(); // Cash
          	
          	  
          	  try 
          	  {
          	    Double w = Double.parseDouble(textFieldValue2);
          	  Double c = Double.parseDouble(textFieldValue3);
          	    validator v= new validator();
          	  int x= jList1AddRcm.getSelectedIndex();
          	  
     
          	              v.addNewRcm(textFieldValue1,x,w,c);
          	            JOptionPane.showMessageDialog(null, "New Recycle Machine Added", "ALERT", 1); 
          	           
          	  }
          	catch(NumberFormatException e) {
          		JOptionPane.showMessageDialog(null,"Please Enter Numbers only","TITLE",JOptionPane.WARNING_MESSAGE);
          	 } catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			};
            }
        });

        jLabel6AddRcm.setText("Weight");
        jLabel6AddRcm.setBounds(20, 120, 60, 14);
        jLayeredPane1AddRcm.add(jLabel6AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);

        jLabel5AddRcm.setText("Cash");
        jLabel5AddRcm.setBounds(240, 120, 60, 14);
        jLayeredPane1AddRcm.add(jLabel5AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);

        jLabel4AddRcm.setText("Items Accepted");
        jLabel4AddRcm.setBounds(10, 30, 100, 20);
        jLayeredPane1AddRcm.add(jLabel4AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);
       jTextField2AddRcm.setBounds(280, 120, 90, 20);
        jLayeredPane1AddRcm.add(jTextField2AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);

        jLabel3AddRcm.setText("Location");
        jLabel3AddRcm.setBounds(10, 10, 100, 14);
        jLayeredPane1AddRcm.add(jLabel3AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);

        jList1AddRcm.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "PAPER", "GLASS", "PLASTIC", "ALUMINIUM" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1AddRcm.setViewportView(jList1AddRcm);

        jScrollPane1AddRcm.setBounds(110, 30, 90, 80);
        jLayeredPane1AddRcm.add(jScrollPane1AddRcm, javax.swing.JLayeredPane.DRAG_LAYER);

        getContentPane().add(jLayeredPane1AddRcm);
        jLayeredPane1AddRcm.setBounds(0, 10, 900, 500);
        

        
        ///***********************************service*****************
/*        jComboBox2Service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
          	     Joption
            }
        });*/
        jButton1Service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	validator val1=new validator();
          	     int i = 0;
				try {
					i = val1.service(jComboBox2Service.getSelectedIndex(),(String) jComboBox1Service.getSelectedItem(),jTextField1Service.getText());
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
          	     if(i==1)
          	     {
          	    	JOptionPane.showMessageDialog(null,"SUCCESS","TITLE",JOptionPane.WARNING_MESSAGE);
          	     }
          	     else
          	     {
          	    	JOptionPane.showMessageDialog(null,"FAIL","TITLE",JOptionPane.WARNING_MESSAGE);
          	     }
            }
        });
        String[][] s1=val.getRcmDetails();
        String[] l=new String[s1.length];
        for(int i=0;i<s1.length;i++)
        {
        	l[i]=s1[i][0];
        }
        jLabel2Service.setText("Status");
        jLabel2Service.setBounds(200, 20, 50, 14);
        jLayeredPane1Service.add(jLabel2Service, javax.swing.JLayeredPane.DEFAULT_LAYER);
        

        jLabel1Service.setText("Cash");
        jLabel1Service.setBounds(200, 25, 50, 70);
        jLayeredPane1Service.add(jLabel1Service, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1Service.setBounds(270, 50, 60, 25);
        //jTextField1Service.setText(s1[0][2]);
        jLayeredPane1Service.add(jTextField1Service, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        
        jComboBox1Service.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVE", "DEACTIVE" }));
        jComboBox1Service.setBounds(270, 20, 100, 20);
        /*  if(s1[0][1].equalsIgnoreCase("ACTIVE"))
        {
        	jComboBox1Service.setSelectedItem("ACTIVE");
        }
        else
        {
        	jComboBox1Service.setSelectedItem("DEACTIVE");
        }*/
      
        jLayeredPane1Service.add(jComboBox1Service, javax.swing.JLayeredPane.DEFAULT_LAYER);
      
        jComboBox2Service.setModel(new javax.swing.DefaultComboBoxModel(l));

        
        jScrollPane1Service.setViewportView(jComboBox2Service);

        jScrollPane1Service.setBounds(20, 10, 160, 130);
        jLayeredPane1Service.add(jScrollPane1Service, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1Service.setText("service");
        jButton1Service.setBounds(210, 120, 67, 23);
        jLayeredPane1Service.add(jButton1Service, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1Service);
        jLayeredPane1Service.setBounds(0, 0, 400, 160);
//*********************************************************************
        String[][] months=new String[][]{
            	{"JAN","31"},
            	{"FEB","28"},
            	{"MAR","31"},
            	{"APR","30"},
            	{"MAY","31"},
            	{"JUN","30"},
            	{"JUL","31"},
            	{"AUG","31"},
            	{"SEP","30"},
            	{"OCT","31"},
            	{"NOV","30"},
            	{"DEC","31"}};
            String[] monthName=new String[12];
            for(int i=0;i<12;i++)
            {
            	monthName[i]=months[i][0];
            }
             String[] year=new String[] {"2014","2013"};
        jButton5Stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButton2Stat.setSelected(false);
            	//String[] day;
            	JLabel label = new JLabel("Selected Date:");
            	final JTextField text = new JTextField(20);
            	 JButton b = new JButton("Add");
                 JPanel p = new JPanel();
                 p.add(label);
                 p.add(text);
                 p.add(b);
                 final JFrame f = new JFrame();
                 f.getContentPane().add(p);
                 f.pack();
                 f.setVisible(true);
                 text.setText(new DatePicker(f).setPickedDate());
            	//jNewButton3Stat.setText(new DatePicker().setPickedDate());
            	b.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    	f.dispose();
                 try {
 					final mainWindow f1=new mainWindow();
 					f1.setDate1(text.getText());
 				} catch (SQLException e) {
 					// TODO Auto-generated catch block
 					e.printStackTrace();
 				}
                    }
            	});
            }
        });
        
       /* jButton6Stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButton2Stat.setSelected(false);
            	//String[] day;
            	JLabel label = new JLabel("Selected Date:");
            	final JTextField text = new JTextField(20);
            	 JButton b = new JButton("popup");
                 JPanel p = new JPanel();
                 p.add(label);
                 p.add(text);
                 p.add(b);
                 final JFrame f = new JFrame();
                 f.getContentPane().add(p);
                 f.pack();
                 f.setVisible(true);
                 text.setText(new DatePicker(f).setPickedDate());                     
                 try {
					mainWindow f1=new mainWindow();
					f1.setDate2(text.getText());
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
                 
            	//jNewButton4Stat.setText(new DatePicker(f).setPickedDate());

            }
        });*/
        
        jRadioButton1Stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButton2Stat.setSelected(false);
            	jLabel3Stat.setText("Week");
            	//JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
            }
        });
        //graph
        //public graph(String C,String type,Date Strt, String interval, string r){
        
        jButton1Stat.addActionListener(new java.awt.event.ActionListener() {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {

        		 String w="WEEK";
        		 if(jRadioButton1Stat.isSelected()!=true)
        		 {
        			 w="DAY";
        		 }
             	String str=""+jComboBox2Stat.getSelectedItem()+","+jComboBox2Stat.getSelectedItem()+","+jComboBox1Stat.getSelectedItem()+"";
             	try {
					graph gp=new graph("No Of times RCM was empties",w,jComboBox1Stat.getSelectedItem().toString(),"f");
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        	 }
        	 });
        jButton2Stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	JOptionPane.showMessageDialog(null,jComboBox2Stat.getSelectedItem()+"-"+jComboBox1Stat.getSelectedItem()+"-"+jComboBox3Stat.getSelectedItem(),"Date",JOptionPane.WARNING_MESSAGE);

            	@SuppressWarnings("deprecation")
				Date start = new Date(D1+",0,0,0,0");
            	graph gp=new graph("No Of times RCM was empties",jNewButton4Stat.getSelectedItem().toString(),start, jButton6Stat.getText().toString());
            	
            }
        });
        jRadioButton2Stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButton1Stat.setSelected(false);
            	jLabel3Stat.setText("Day");
            	String[] days = null;
            	switch(jComboBox2Stat.getSelectedItem().toString())
            	{
            		case "JAN":
            		case "MAR":
            		case "MAY":
            		case "AUG":
            		case "JUL":
            		case "OCT":
            		case "DEC": 
            			 days=new String[31];
            		break;
            		case "FEB":
            			days=new String[28];
            			break;
            		case "APR":
            		case "JUN":
            		case "SEP":
            		case "NOV":
            			days=new String[30];
            			default : break;
            			
            					
            	}
            	for(int i=0;i<days.length;i++)
            	{
            		days[i]=""+i+1+"";
            	}
            	jComboBox1Stat.setModel(new javax.swing.DefaultComboBoxModel(days));
            }
        });
        
        jLabel1Stat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1Stat.setText("usage statistics");
        jLabel1Stat.setBounds(20, 20, 100, 14);
        jLayeredPane1Stat.add(jLabel1Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2Stat.setText("Month");
        jLabel2Stat.setBounds(20, 40, 70, 20);
        jLayeredPane1Stat.add(jLabel2Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jRadioButton1Stat.setText("Weekly");
        jRadioButton1Stat.setBounds(10, 70, 61, 23);
        jLayeredPane1Stat.add(jRadioButton1Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jRadioButton2Stat.setText("Day");
        jRadioButton2Stat.setBounds(110, 70, 45, 23);
        jLayeredPane1Stat.add(jRadioButton2Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3Stat.setText("Weeks/Day");
        jLabel3Stat.setBounds(20, 100, 100, 14);
        jLayeredPane1Stat.add(jLabel3Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4Stat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4Stat.setText("No Of times RCM was empties");
        jLabel4Stat.setBounds(20, 130, 220, 14);
        jLayeredPane1Stat.add(jLabel4Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5Stat.setText("Start Date");
        jButton5Stat.setBounds(20, 160, 100, 25);
        jLayeredPane1Stat.add(jButton5Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);


         jNewButton4Stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WEEK", "DAY" }));
        jNewButton4Stat.setBounds(260, 147, 90, 27);
        jLayeredPane1Stat.add(jNewButton4Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        jButton6Stat.setText("          ");
        jButton6Stat.setBounds(184, 155, 50, 25);
        jLayeredPane1Stat.add(jButton6Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1Stat.setText("Show");
        jButton1Stat.setBounds(260, 90, 59, 23);
        jLayeredPane1Stat.add(jButton1Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2Stat.setText("Show");
        jButton2Stat.setBounds(400, 150, 59, 23);
        jLayeredPane1Stat.add(jButton2Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1Stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jComboBox1Stat.setBounds(110, 100, 70, 20);
        jLayeredPane1Stat.add(jComboBox1Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);
         
        jComboBox2Stat.setModel(new javax.swing.DefaultComboBoxModel(monthName));
        jComboBox2Stat.setBounds(110, 40, 70, 20);
        jLayeredPane1Stat.add(jComboBox2Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7Stat.setText("Year");
        jLabel7Stat.setBounds(200, 40, 50, 14);
        jLayeredPane1Stat.add(jLabel7Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox3Stat.setModel(new javax.swing.DefaultComboBoxModel(year));
        jComboBox3Stat.setBounds(260, 40, 70, 20);
        jLayeredPane1Stat.add(jComboBox3Stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1Stat);
        jLayeredPane1Stat.setBounds(0, -50, 400, 250);
       // ********************************************************************
        //
        ////////////////////////////////////////////////////////////////
        jTabbedPane1.addTab("RCM LIST", jScrollPane1);
        jTabbedPane1.addTab("ADD NEW RCM", jLayeredPane1AddRcm);
		jTabbedPane1.addTab("SERVICE", jLayeredPane1Service);
		jTabbedPane1.addTab("STATISTICS", jLayeredPane1Stat);
        //////////////////////////////////////////////////////////////////

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 40));
        //***************** Code for panel 1
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, 50, 50, 50)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        ); 
        
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBounds(400, 40, 600, 300);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

       
        jLabel6.setText("");   //Dustbin
      //  jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 90, 100, 100); 
     

        jLabel11.setText("");   //Dustbin
        //jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 90, 100, 100);

        
        imagePanel.setBounds(0, 0, 1400, 750);
        jLayeredPane1.add(imagePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
    
   	        rcmid = new JLabel("RCM ID:");    // AddRCM
   	        rcmid.setBounds(0, 0, 20, 20);
   	        jPanel50.add(rcmid);
   	        
   	        enterrcmid = new JTextField(10);
   	        jPanel50.add(enterrcmid,javax.swing.JLayeredPane.DRAG_LAYER);
   	        
   	        
   	        location = new JLabel("LOCATION:");   // AddRCM
   	        location.setBounds(5, 5, 20, 10);
   	        jPanel50.add(location);
   	        enterlocation = new JTextField(10);  
   	        jPanel50.add(enterlocation);
   	        
   	        
   	        status = new JLabel("STATUS:");   // AddRCM
   	        jPanel50.add(status);
   	        enterstatus = new JTextField(10);  
   	        jPanel50.add(enterstatus);
   	        
   	        weight = new JLabel("MAXIMUM WEIGHT");  // AddRCM
   	        jPanel50.add(weight);
   	        enterrcmweight = new JTextField(10); 
   	        jPanel50.add(enterrcmweight);
   	        
   	        
   	        
   	         update= new JButton("UPDATE");   // AddRCM
   	         jPanel50.add(update);
   	         cancel = new JButton("CANCEL"); 
   	         jPanel50.add(cancel);
   	         
   	         

   	         update.addActionListener(new ActionListener() {  //Add RCM
   	        	  
   	             public void actionPerformed(ActionEvent e) {  
   	                 String newrcmid = enterrcmid.getText();  
   	                 String newlocation = enterlocation.getText();
   	                 String newstatus = enterstatus.getText(); 
   	                 String newweight = enterrcmweight.getText();
   	                 String newvolume = enterrcmvolume.getText();  
   	                 int intID = Integer.parseInt(newrcmid);  

   	                
   	                 
   	                 try {  
   	                	 sqlConnection connect2= new sqlConnection();
   	                	 Connection conn=connect2.connect();
   	                
   	                     stm = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);  
   	                   
   	                     String sql ="INSERT INTO rcm(rcm_id,location,status,max_weight,max_volume) VALUES ('"+intID+"','"+newlocation+"','"+newstatus+"',"+newweight+",'"+newvolume+"')";  
   	                     stm.executeUpdate(sql);  
   	                    
   	                     JOptionPane.showMessageDialog(null, "New Recycle Machine Added", "ALERT", 1);  
   	                 } catch (SQLException e1) {  
   	                     e1.printStackTrace();  
   	                 }  
   	                   
   	             }  
   	         }); 
   	      
         
             //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
             //////			CODE FOR RCM1
             /////
             /////
             ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  	         
   	         jPanel1RCM1.setBackground(new java.awt.Color(255, 255, 255));
   	      validator v=new validator();
   	      ResultSet res1= v.getItemsRecycledForRCM(1);
   	      ResultSetMetaData md1 = res1.getMetaData();
   	      ResultSet res2=v.getItemsRecycledForRCM(2);
   	      ResultSetMetaData md2 = res2.getMetaData();

	   	    Vector columnNames1 = v.getCol(res1);
	   	    Vector columnNames2 = v.getCol(res2);
	   	    Vector data1 = v.getRow(res1,md1.getColumnCount());
		    Vector data2 = v.getRow(res2,md2.getColumnCount());
   	      // columnNames.addElement("edit");

   	       //  Get row data

   	  	   JTable jTable1RCM1 = new JTable(data1, columnNames1)
   	       {
   	           public Class getColumnClass(int column)
   	           {
   	               for (int row = 0; row < getRowCount(); row++)
   	               {
   	                   Object o = getValueAt(row, column);

   	                   if (o != null)
   	                   {
   	                       return o.getClass();
   	                   }
   	               }

   	               return Object.class;
   	           }
   	       };
   	  	   JTable jTable1RCM2 = new JTable(data2, columnNames2)
   	       {
   	           public Class getColumnClass(int column)
   	           {
   	               for (int row = 0; row < getRowCount(); row++)
   	               {
   	                   Object o = getValueAt(row, column);

   	                   if (o != null)
   	                   {
   	                       return o.getClass();
   	                   }
   	               }

   	               return Object.class;
   	           }
   	       };
          jLabel1RCM1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
          jLabel1RCM1.setText("                                                    RCM : ( ID - 01, Location - Santa Barbara )");
          Border border = BorderFactory.createLineBorder(Color.BLACK, 2);

          jPanel1RCM1.setBorder(border);

          jComboBox1RCM1.setModel(new javax.swing.DefaultComboBoxModel(v.getListOfAcceptableItems(1)));

          jLabel2RCM1.setText("Item");

          jLabel3RCM1.setText("weight");

          jRadioButton1RCM1.setSelected(true);
          jRadioButton1RCM1.setText("Cash");

          jRadioButton2RCM1.setText("Coupon");

          jLabel4RCM1.setText("");

          jLabel5RCM1.setText("");

          jLabel6RCM1.setText("Transaction");
          
          jScrollPane1RCM1.setViewportView(jTable1RCM1);

          button1RCM1.setLabel("Multiple Item");
          button1RCM1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  //JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });

          // Event on Recycle button RCM 1
          jButton4RCM1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 // if()
            	  String textFieldValue =jTextField1RCM1.getText();
            	/*  try 
            	  {
            	    int val = Integer.parseInt(textFieldValue);*/
            	    validator v= new validator();
            	    int value=1;
            	  /*  v.Recycle(value, textFieldValue, jComboBox1RCM1.getSelectedItem().toString(), Double.parseDouble(weight.getText()));
            	  }
            	catch(NumberFormatException e) {
            		//JOptionPane.showMessageDialog(null,"Please Enter Numbers only","TITLE",JOptionPane.WARNING_MESSAGE);
            	 }*/
            	  //JOptionPane.showMessageDialog(null,textFieldValue,"TITLE",JOptionPane.WARNING_MESSAGE);
            	 // JOptionPane.showMessageDialog(null,jComboBox1RCM1.getSelectedItem(),"TITLE",JOptionPane.WARNING_MESSAGE);
            	  //JOptionPane.showMessageDialog(null,jRadioButton1RCM1.isSelected(),"TITLE",JOptionPane.WARNING_MESSAGE);
            	  
              }
          });
          // Event on Clear button RCM 1
          jButton1RCM1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 // JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });
          
          // Event on Back button RCM 1
          jButton2RCM1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });
          
          // Event on Exit button RCM 1
          jButton3RCM1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });
          
          jComboBox1RCM1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
               	  String s=(String) jComboBox1RCM1.getSelectedItem();
              	switch(s)
              	{            	
              		case "PLASTIC": jLabel8RCM1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\Plastics.jpg"));
              						break;
              		case "PAPER": jLabel8RCM1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\paper.jpg"));
              						break;
              		case "ALUMINIUM": jLabel8RCM1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\coke-can-007.jpg"));
              						break;
              		case "GLASS": jLabel8RCM1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\brown-glass-beverage-containers1.jpg"));
              						break;
              		default : jLabel8RCM1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\paper.jpg"));
              						break;
              	}
              }
          });
          //
          jTable1RCM1.addMouseListener(new java.awt.event.MouseAdapter() {
      	    @Override
      	    public void mouseClicked(java.awt.event.MouseEvent evt) {
      	        int row = jTable1.rowAtPoint(evt.getPoint());
      	        int col = jTable1.columnAtPoint(evt.getPoint());
      	        if(col==1)
      	        {
            	  JOptionPane.showMessageDialog(null,row,"TITLE",JOptionPane.WARNING_MESSAGE);
      	        }
      	    }
        });
          //label1RCM1.setText("% of cash");

          jButton1RCM1.setText("Clear");

          jButton2RCM1.setText("Back");

          jButton3RCM1.setText("Exit");

          jButton4RCM1.setText("Recycle");

          //jLabel7RCM1.setText("jLabel7RCM1");

          //jLabel8RCM1.setText("jLabel8RCM1");

          javax.swing.GroupLayout jPanel1RCM1Layout = new javax.swing.GroupLayout(jPanel1RCM1);
          jPanel1RCM1.setLayout(jPanel1RCM1Layout);
         // Component jTextField1RCM1 = null;
		jPanel1RCM1Layout.setHorizontalGroup(
              jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                          .addGap(17, 17, 17)
                          .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(jLabel2RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel3RCM1))
                          .addGap(37, 37, 37)
                          .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                      .addComponent(jComboBox1RCM1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addComponent(jTextField1RCM1))
                                  .addGap(18, 18, 18)
                                  .addComponent(jLabel4RCM1))
                              .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                          .addGap(32, 32, 32)
                                          .addComponent(jRadioButton1RCM1)
                                          .addGap(18, 18, 18)
                                          .addComponent(jRadioButton2RCM1))
                                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                          .addComponent(jLabel5RCM1)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(jButton4RCM1)))
                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                          .addComponent(jButton1RCM1)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jButton2RCM1))
                                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                          .addComponent(textField1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(label1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(jButton3RCM1))
                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                          .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                  .addContainerGap()
                                  .addComponent(button1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                                  .addContainerGap()
                                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addComponent(jLabel6RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(jScrollPane1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                          .addGap(0, 19, Short.MAX_VALUE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      //.addComponent(jLabel7RCM1)
                      //.addComponent(jLabel8RCM1)
                		  )
                  .addGap(71, 71, 71))
              .addComponent(jLabel1RCM1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          jPanel1RCM1Layout.setVerticalGroup(
              jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                  .addComponent(jLabel1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel6RCM1)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(jScrollPane1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                          .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(button1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                  .addComponent(textField1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(jRadioButton1RCM1)
                                      .addComponent(jRadioButton2RCM1)))
                              .addComponent(label1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
  							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jComboBox1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel2RCM1))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jTextField1RCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel3RCM1)
                              .addComponent(jLabel4RCM1))
                          .addGap(19, 19, 19))
                      .addGroup(jPanel1RCM1Layout.createSequentialGroup()
                          .addGap(76, 76, 76)
                         // .addComponent(jLabel8RCM1)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                  .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel5RCM1)
                      .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jButton1RCM1)
                          .addComponent(jButton3RCM1)
                          .addComponent(jButton2RCM1)
                          .addComponent(jButton4RCM1)))
                  //.addGap(11, 11, 11)
                 // .addGroup(jPanel1RCM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  //       .addComponent(jLabel7RCM1,javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(11, 11, 11))
          );
          jLabel7RCM1.setBounds(460,200,150,150);
          jPanel1RCM1.add(jLabel7RCM1, javax.swing.JLayeredPane.DRAG_LAYER);
          jLabel8RCM1.setBounds(470,11,150,150);
          jPanel1RCM1.add(jLabel8RCM1, javax.swing.JLayeredPane.DRAG_LAYER);
          jPanel1RCM1.setBounds(50, 350, 610, 352);  //***
          jLayeredPane1.add(jPanel1RCM1, javax.swing.JLayeredPane.DRAG_LAYER);
    	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
          ///////////					RCM2
          //////////
          ///////////
          //////////////////////////////////////////////////////////////////////////////////////////////////////////////



          jPanel1RCM2.setBackground(new java.awt.Color(255, 255, 255));

          jPanel1RCM2.setBorder(border);
          jLabel1RCM2.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
          jLabel1RCM2.setText("                                                    RCM : ( ID - 02, Location - Santa Clara )");

          validator v1=new validator();
          jComboBox1RCM2.setModel(new javax.swing.DefaultComboBoxModel(v1.getListOfAcceptableItems(2)));

          jLabel2RCM2.setText("Item");

          jLabel3RCM2.setText("weight");

          jRadioButton1RCM2.setSelected(true);
          jRadioButton1RCM2.setText("Cash");

          jRadioButton2RCM2.setText("Coupon");

          jLabel4RCM2.setText(""); //rate

          jLabel5RCM2.setText(""); //amount

          jLabel6RCM2.setText("Transaction");

          jScrollPane1RCM2.setViewportView(jTable1RCM2);

          button1RCM2.setLabel("Multiple Item");
          button1RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	//  JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
            	 // jComboBox1RCM2.

                  jRadioButton1RCM2.setSelected(true);

                  jRadioButton2RCM2.setSelected(false);

                  jLabel4RCM2.setText("");

                  jLabel5RCM2.setText("");
              }
          });
/*
          textField1RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  textField1RCM2ActionPerformed(evt);
              }
          });*/
          // Event for Recycle button in RCM 2
          jButton4RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  String textFieldValue =jtextField1RCM2.getText();
/*            	  try 
            	  {
            	    int val = Integer.parseInt(textFieldValue);*/
            	    validator v= new validator();
            	    int value=2;
            	    v.Recycle(value, textFieldValue, jComboBox1RCM2.getSelectedItem().toString(), Double.parseDouble(weight.getText()));
            	/*  }
            	catch(NumberFormatException e) {
            		//JOptionPane.showMessageDialog(null,"Please Enter Numbers only","TITLE",JOptionPane.WARNING_MESSAGE);
            	 } 
            	  */
              }
          });
          
          // Event on Recycle button RCM 1
          jButton4RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  //JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });
          // Event on Clear button RCM 1
          jButton1RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 // JOptionPane.showMessageDialog(null,"ALL Clear","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });
          
          // Event on Back button RCM 1
          jButton2RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  //JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });
          
          // Event on Exit button RCM 1
          jButton3RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  JOptionPane.showMessageDialog(null,"ALERT MESSAGE","TITLE",JOptionPane.WARNING_MESSAGE);
              }
          });
          // Event on item combo box
          jComboBox1RCM2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
            	  String s=(String) jComboBox1RCM2.getSelectedItem();
                	switch(s)
                	{
                	
                		case "PLASTIC": jLabel8RCM2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\Plastics.jpg"));
                						break;
                		case "PAPER": jLabel8RCM2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\paper.jpg"));
                						break;
                		case "ALUMINIUM": jLabel8RCM2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\coke-can-007.jpg"));
                						break;
                		case "GLASS": jLabel8RCM2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\brown-glass-beverage-containers1.jpg"));
                						break;
                		default : jLabel8RCM2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Priyanka\\Desktop\\paper.jpg"));
                						break;
                	}
              }
          });
          //

          jTable1RCM2.addMouseListener(new java.awt.event.MouseAdapter() {
        	    @Override
        	    public void mouseClicked(java.awt.event.MouseEvent evt) {
        	        int row = jTable1.rowAtPoint(evt.getPoint());
        	        int col = jTable1.columnAtPoint(evt.getPoint());
          	        if(col==1)
          	        {
                	  JOptionPane.showMessageDialog(null,row,"TITLE",JOptionPane.WARNING_MESSAGE);
          	        }

        	    }
          });
          
          jLabel4RCM2.addMouseListener(new java.awt.event.MouseAdapter() {
      	    @Override
      	    public void mouseClicked(java.awt.event.MouseEvent evt) {
      	       validator s=new validator();
      	       Object r=s.getObj(1);
      	       
      	    }
        });
          //label1RCM2.setText("% of cash");

          jButton1RCM2.setText("Clear");

          jButton2RCM2.setText("Back");

          jButton3RCM2.setText("Exit");

          jButton4RCM2.setText("Recycle");

          javax.swing.GroupLayout jPanel1RCM2Layout = new javax.swing.GroupLayout(jPanel1RCM2);
          jPanel1RCM2.setLayout(jPanel1RCM2Layout);
          jPanel1RCM2Layout.setHorizontalGroup(
              jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                          .addGap(17, 17, 17)
                          .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(jLabel2RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel3RCM2))
                          .addGap(37, 37, 37)
                          .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                      .addComponent(jComboBox1RCM2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addComponent(jtextField1RCM2))
                                  .addGap(18, 18, 18)
                                  .addComponent(jLabel4RCM2))
                              .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                          .addGap(32, 32, 32)
                                          .addComponent(jRadioButton1RCM2)
                                          .addGap(18, 18, 18)
                                          .addComponent(jRadioButton2RCM2))
                                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                          .addComponent(jLabel5RCM2)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(jButton4RCM2)))
                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                          .addComponent(jButton1RCM2)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jButton2RCM2))
                                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                          //.addComponent(textField1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(label1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(jButton3RCM2))
                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                          .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                  .addContainerGap()
                                  .addComponent(button1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                                  .addContainerGap()
                                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addComponent(jLabel6RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(jScrollPane1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                          .addGap(0, 19, Short.MAX_VALUE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                		  //.addGap(50, 50, 50)
                      //.addComponent(jLabel7RCM2)
                      //.addComponent(jLabel8RCM2)
                		  )
                  .addGap(71, 71, 71))
              .addComponent(jLabel1RCM2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          jPanel1RCM2Layout.setVerticalGroup(
              jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                  .addComponent(jLabel1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel6RCM2)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(jScrollPane1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                          .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(button1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                 // .addComponent(textField1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(jRadioButton1RCM2)
                                      .addComponent(jRadioButton2RCM2)))
                              .addComponent(label1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
  							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jComboBox1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel2RCM2))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jtextField1RCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel3RCM2)
                              .addComponent(jLabel4RCM2))
                          .addGap(19, 19, 19))
                      .addGroup(jPanel1RCM2Layout.createSequentialGroup()
                          .addGap(76, 76, 76)
                          //.addComponent(jLabel8RCM2)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                  .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel5RCM2)
                      .addGroup(jPanel1RCM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jButton1RCM2)
                          .addComponent(jButton3RCM2)
                          .addComponent(jButton2RCM2)
                          .addComponent(jButton4RCM2)))
                  .addGap(11, 11, 11))
          );

          jLabel7RCM2.setBounds(460,200,150,150);
          jPanel1RCM2.add(jLabel7RCM2, javax.swing.JLayeredPane.DRAG_LAYER);
          jLabel8RCM2.setBounds(470,11,150,150);
          jPanel1RCM2.add(jLabel8RCM2, javax.swing.JLayeredPane.DRAG_LAYER);
          jPanel1RCM2.setBounds(700, 350, 600, 352);
          jLayeredPane1.add(jPanel1RCM2, javax.swing.JLayeredPane.DRAG_LAYER);
          
        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 2147483647, 2147483647);
        
        
      
        
        
        pack();
    }

   public void load() throws SQLException
   {
	   java.awt.EventQueue.invokeLater(new Runnable() {

           public void run() {
               try {
            	Connection conn=connnect.connect();
           		 ResultSet item= sql.getRcm(conn);
           		 ResultSetMetaData md = item.getMetaData();
           	   	 int count = md.getColumnCount();
           	   	 while(item.next()){
           	   		count = item.getInt("count");
           	   		System.out.println(count);
           		}
           	   	int i=0;
           		 String[]ListRCM= new String[count];
           		 while(item.next()){
           			 ListRCM[i] = item.getString("location");
           			 i++;
           		}
           		 conn.close();
           		 RCM=ListRCM;
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
           }
       });
	   
   }
   


    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel11;
  
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
   private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
  
    private javax.swing.JLabel rcmid ;   // AddRCM
    private javax.swing.JLabel location; // AddRCM
    private javax.swing.JLabel status; // AddRCM
    private javax.swing.JLabel weight; // AddRCM
    private javax.swing.JLabel volume; // AddRCM
    private javax.swing.JTextField enterrcmid ; // AddRCM
    private javax.swing.JTextField enterlocation; // AddRCM
    private javax.swing.JTextField enterstatus; // AddRCM
    private javax.swing.JTextField enterrcmweight; // AddRCM
    private javax.swing.JTextField enterrcmvolume; // AddRCM
    private javax.swing.JButton update; // AddRCM
    private javax.swing.JButton cancel;  // AddRCM
    private javax.swing.JPanel jPanel50;
    
	private java.awt.Button button1RCM1;
    private javax.swing.JButton jButton1RCM1;
    private javax.swing.JButton jButton2RCM1;
    private javax.swing.JButton jButton3RCM1;
    private javax.swing.JButton jButton4RCM1;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox1RCM1;
    private javax.swing.JLabel jLabel1RCM1;
    private javax.swing.JLabel jLabel2RCM1;
    private javax.swing.JLabel jLabel3RCM1;
    private javax.swing.JLabel jLabel4RCM1;
    private javax.swing.JLabel jLabel5RCM1;
    private javax.swing.JLabel jLabel6RCM1;
    private javax.swing.JLabel jLabel7RCM1;
    private javax.swing.JLabel jLabel8RCM1;
    private javax.swing.JPanel jPanel1RCM1;
    private javax.swing.JRadioButton jRadioButton1RCM1;
    private javax.swing.JRadioButton jRadioButton2RCM1;
    private javax.swing.JScrollPane jScrollPane1RCM1;
   // private javax.swing.JTable jTable1RCM1;
    private javax.swing.JTextField jTextField1RCM1;
    private java.awt.Label label1RCM1;
    private java.awt.TextField textField1RCM1;
    
	private java.awt.Button button1RCM2;
    private javax.swing.JButton jButton1RCM2;
    private javax.swing.JButton jButton2RCM2;
    private javax.swing.JButton jButton3RCM2;
    private javax.swing.JButton jButton4RCM2;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox1RCM2;
    private javax.swing.JLabel jLabel1RCM2;
    private javax.swing.JLabel jLabel2RCM2;
    private javax.swing.JLabel jLabel3RCM2;
    private javax.swing.JLabel jLabel4RCM2;
    private javax.swing.JLabel jLabel5RCM2;
    private javax.swing.JLabel jLabel6RCM2;
    private javax.swing.JLabel jLabel7RCM2;
    private javax.swing.JLabel jLabel8RCM2;
    private javax.swing.JLayeredPane jLayeredPane1RCM2;
    private javax.swing.JPanel jPanel1RCM2;
    private javax.swing.JRadioButton jRadioButton1RCM2;
    private javax.swing.JRadioButton jRadioButton2RCM2;
    private javax.swing.JScrollPane jScrollPane1RCM2;
    private javax.swing.JTextField jtextField1RCM2;
    private java.awt.Label label1RCM2;
    private java.awt.TextField textField1RCM2;
    
	private javax.swing.JButton jButton1AddRcm;
    private javax.swing.JButton jButton2AddRcm;
    private javax.swing.JLabel jLabel1AddRcm;
    private javax.swing.JLabel jLabel3AddRcm;
    private javax.swing.JLabel jLabel4AddRcm;
    private javax.swing.JLabel jLabel5AddRcm;
    private javax.swing.JLabel jLabel6AddRcm;
    private javax.swing.JLayeredPane jLayeredPane1AddRcm;
    private javax.swing.JList jList1AddRcm;
    private javax.swing.JScrollPane jScrollPane1AddRcm;
    private javax.swing.JTextField jTextField2AddRcm;
    private javax.swing.JTextField jTextField3AddRcm;
    private javax.swing.JTextField jTextField4AddRcm;
    
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox1Service;
    private javax.swing.JLabel jLabel1Service;
    private javax.swing.JLabel jLabel2Service;
    @SuppressWarnings("rawtypes")
	private javax.swing.JList jList1Service;
    private javax.swing.JScrollPane jScrollPane1Service;
    private javax.swing.JTextField jTextField1Service;
    private javax.swing.JLayeredPane jLayeredPane1Service;
    private javax.swing.JButton jButton1Service;
    
    
	private javax.swing.JButton jButton1Stat;
	private javax.swing.JButton jButton2Stat;
	private javax.swing.JComboBox jComboBox1Stat;
	private javax.swing.JComboBox jComboBox2Stat;
	private javax.swing.JComboBox jComboBox3Stat;
	private javax.swing.JLabel jLabel1Stat;
	private javax.swing.JLabel jLabel2Stat;
	private javax.swing.JLabel jLabel3Stat;
	private javax.swing.JLabel jLabel4Stat;
	private javax.swing.JButton jButton5Stat;
	private javax.swing.JTextField jButton6Stat;
	private javax.swing.JLabel jLabel7Stat;
	private javax.swing.JLayeredPane jLayeredPane1Stat;
	private javax.swing.JRadioButton jRadioButton1Stat;
	private javax.swing.JRadioButton jRadioButton2Stat;
	private javax.swing.JTextField jNewButton3Stat;
	private javax.swing.JComboBox jNewButton4Stat;
	private javax.swing.JButton jButton2Service;
	private javax.swing.JComboBox jComboBox2Service;
    // End of variables declaration
    
    static class ImagePanel extends JPanel {
        private Image image;
        ImagePanel(Image image) {
            this.image = image;
        }
        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image,0,0,getWidth(),getHeight(),this);
        }
    }

}
